//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodPressureTracker.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class bloodPressure
    {
        public int userId { get; set; }
        public int dietId { get; set; }
        [Required(ErrorMessage ="Sample Required")]
        public string pressureSample { get; set; }
        public string dateTime { get; set; }
        public int RemainTime { get; set; }
        public Reminder RemindOption { get; set; }

        public bool RememberEmail { get; set; }


        public virtual diet diet { get; set; }
        public virtual user user { get; set; }
    }

    public enum Reminder
    {
        OneMinute,
        OneHour,
        Twohours,
        ThreeHours
    }
}
