//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodPressureTracker.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.bloodPressures = new HashSet<bloodPressure>();
        }
    
        public int id { get; set; }
        [Required(ErrorMessage = "User Name is Required")]
        public string name { get; set; }
        [Required(ErrorMessage = "Weight is Required")]
        public int weight { get; set; }
        [Required(ErrorMessage = "Age is Required")]
        public int age { get; set; }
        [Required(ErrorMessage = "Gender is Required")]
        public string gender { get; set; }
        [Required(ErrorMessage = "Email is Required")]
        [DataType(DataType.EmailAddress)]
        public string email { get; set; }
        [Required(ErrorMessage ="Password is Required")]
        [DataType(DataType.Password)]
        public string password { get; set; }
        [Required(ErrorMessage = "Blood Sample is Required")]
        public string BPsample { get; set; }

        public string LoginErrorMsg { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bloodPressure> bloodPressures { get; set; }
    }
}
