//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodPressureTracker.WCFServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFServiceReference.IWCFService")]
    public interface IWCFService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWCFService/UpdateInformation")]
        void UpdateInformation(int id, string name, int weight, int age, char gender);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWCFService/UpdateInformation")]
        System.Threading.Tasks.Task UpdateInformationAsync(int id, string name, int weight, int age, char gender);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/ViewInfo", ReplyAction="http://tempuri.org/IWCFService/ViewInfoResponse")]
        System.Data.DataTable ViewInfo(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/ViewInfo", ReplyAction="http://tempuri.org/IWCFService/ViewInfoResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> ViewInfoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/Viewbloodhistory", ReplyAction="http://tempuri.org/IWCFService/ViewbloodhistoryResponse")]
        System.Data.DataTable Viewbloodhistory(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/Viewbloodhistory", ReplyAction="http://tempuri.org/IWCFService/ViewbloodhistoryResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> ViewbloodhistoryAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/ViewDiet", ReplyAction="http://tempuri.org/IWCFService/ViewDietResponse")]
        string ViewDiet(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/ViewDiet", ReplyAction="http://tempuri.org/IWCFService/ViewDietResponse")]
        System.Threading.Tasks.Task<string> ViewDietAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFServiceChannel : BloodPressureTracker.WCFServiceReference.IWCFService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFServiceClient : System.ServiceModel.ClientBase<BloodPressureTracker.WCFServiceReference.IWCFService>, BloodPressureTracker.WCFServiceReference.IWCFService {
        
        public WCFServiceClient() {
        }
        
        public WCFServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void UpdateInformation(int id, string name, int weight, int age, char gender) {
            base.Channel.UpdateInformation(id, name, weight, age, gender);
        }
        
        public System.Threading.Tasks.Task UpdateInformationAsync(int id, string name, int weight, int age, char gender) {
            return base.Channel.UpdateInformationAsync(id, name, weight, age, gender);
        }
        
        public System.Data.DataTable ViewInfo(int id) {
            return base.Channel.ViewInfo(id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ViewInfoAsync(int id) {
            return base.Channel.ViewInfoAsync(id);
        }
        
        public System.Data.DataTable Viewbloodhistory(int id) {
            return base.Channel.Viewbloodhistory(id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ViewbloodhistoryAsync(int id) {
            return base.Channel.ViewbloodhistoryAsync(id);
        }
        
        public string ViewDiet(int id) {
            return base.Channel.ViewDiet(id);
        }
        
        public System.Threading.Tasks.Task<string> ViewDietAsync(int id) {
            return base.Channel.ViewDietAsync(id);
        }
    }
}
