//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodPressureTracker.SignInServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SignInServiceReference.SignInSoap")]
    public interface SignInSoap {
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/signingIn", ReplyAction="*")]
        BloodPressureTracker.SignInServiceReference.signingInResponse signingIn(BloodPressureTracker.SignInServiceReference.signingInRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/signingIn", ReplyAction="*")]
        System.Threading.Tasks.Task<BloodPressureTracker.SignInServiceReference.signingInResponse> signingInAsync(BloodPressureTracker.SignInServiceReference.signingInRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class signingInRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="signingIn", Namespace="http://tempuri.org/", Order=0)]
        public BloodPressureTracker.SignInServiceReference.signingInRequestBody Body;
        
        public signingInRequest() {
        }
        
        public signingInRequest(BloodPressureTracker.SignInServiceReference.signingInRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class signingInRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public signingInRequestBody() {
        }
        
        public signingInRequestBody(string name, string password) {
            this.name = name;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class signingInResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="signingInResponse", Namespace="http://tempuri.org/", Order=0)]
        public BloodPressureTracker.SignInServiceReference.signingInResponseBody Body;
        
        public signingInResponse() {
        }
        
        public signingInResponse(BloodPressureTracker.SignInServiceReference.signingInResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class signingInResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int signingInResult;
        
        public signingInResponseBody() {
        }
        
        public signingInResponseBody(int signingInResult) {
            this.signingInResult = signingInResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SignInSoapChannel : BloodPressureTracker.SignInServiceReference.SignInSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SignInSoapClient : System.ServiceModel.ClientBase<BloodPressureTracker.SignInServiceReference.SignInSoap>, BloodPressureTracker.SignInServiceReference.SignInSoap {
        
        public SignInSoapClient() {
        }
        
        public SignInSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SignInSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SignInSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SignInSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BloodPressureTracker.SignInServiceReference.signingInResponse BloodPressureTracker.SignInServiceReference.SignInSoap.signingIn(BloodPressureTracker.SignInServiceReference.signingInRequest request) {
            return base.Channel.signingIn(request);
        }
        
        public int signingIn(string name, string password) {
            BloodPressureTracker.SignInServiceReference.signingInRequest inValue = new BloodPressureTracker.SignInServiceReference.signingInRequest();
            inValue.Body = new BloodPressureTracker.SignInServiceReference.signingInRequestBody();
            inValue.Body.name = name;
            inValue.Body.password = password;
            BloodPressureTracker.SignInServiceReference.signingInResponse retVal = ((BloodPressureTracker.SignInServiceReference.SignInSoap)(this)).signingIn(inValue);
            return retVal.Body.signingInResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BloodPressureTracker.SignInServiceReference.signingInResponse> BloodPressureTracker.SignInServiceReference.SignInSoap.signingInAsync(BloodPressureTracker.SignInServiceReference.signingInRequest request) {
            return base.Channel.signingInAsync(request);
        }
        
        public System.Threading.Tasks.Task<BloodPressureTracker.SignInServiceReference.signingInResponse> signingInAsync(string name, string password) {
            BloodPressureTracker.SignInServiceReference.signingInRequest inValue = new BloodPressureTracker.SignInServiceReference.signingInRequest();
            inValue.Body = new BloodPressureTracker.SignInServiceReference.signingInRequestBody();
            inValue.Body.name = name;
            inValue.Body.password = password;
            return ((BloodPressureTracker.SignInServiceReference.SignInSoap)(this)).signingInAsync(inValue);
        }
    }
}
