//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodPressureTracker.SignUpServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SignUpServiceReference.SignUpSoap")]
    public interface SignUpSoap {
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/signingUp", ReplyAction="*")]
        BloodPressureTracker.SignUpServiceReference.signingUpResponse signingUp(BloodPressureTracker.SignUpServiceReference.signingUpRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/signingUp", ReplyAction="*")]
        System.Threading.Tasks.Task<BloodPressureTracker.SignUpServiceReference.signingUpResponse> signingUpAsync(BloodPressureTracker.SignUpServiceReference.signingUpRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class signingUpRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="signingUp", Namespace="http://tempuri.org/", Order=0)]
        public BloodPressureTracker.SignUpServiceReference.signingUpRequestBody Body;
        
        public signingUpRequest() {
        }
        
        public signingUpRequest(BloodPressureTracker.SignUpServiceReference.signingUpRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class signingUpRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int weight;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int age;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public char gender;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string bloodPressure;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string password;
        
        public signingUpRequestBody() {
        }
        
        public signingUpRequestBody(string name, int weight, int age, char gender, string bloodPressure, string email, string password) {
            this.name = name;
            this.weight = weight;
            this.age = age;
            this.gender = gender;
            this.bloodPressure = bloodPressure;
            this.email = email;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class signingUpResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="signingUpResponse", Namespace="http://tempuri.org/", Order=0)]
        public BloodPressureTracker.SignUpServiceReference.signingUpResponseBody Body;
        
        public signingUpResponse() {
        }
        
        public signingUpResponse(BloodPressureTracker.SignUpServiceReference.signingUpResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class signingUpResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int signingUpResult;
        
        public signingUpResponseBody() {
        }
        
        public signingUpResponseBody(int signingUpResult) {
            this.signingUpResult = signingUpResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SignUpSoapChannel : BloodPressureTracker.SignUpServiceReference.SignUpSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SignUpSoapClient : System.ServiceModel.ClientBase<BloodPressureTracker.SignUpServiceReference.SignUpSoap>, BloodPressureTracker.SignUpServiceReference.SignUpSoap {
        
        public SignUpSoapClient() {
        }
        
        public SignUpSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SignUpSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SignUpSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SignUpSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BloodPressureTracker.SignUpServiceReference.signingUpResponse BloodPressureTracker.SignUpServiceReference.SignUpSoap.signingUp(BloodPressureTracker.SignUpServiceReference.signingUpRequest request) {
            return base.Channel.signingUp(request);
        }
        
        public int signingUp(string name, int weight, int age, char gender, string bloodPressure, string email, string password) {
            BloodPressureTracker.SignUpServiceReference.signingUpRequest inValue = new BloodPressureTracker.SignUpServiceReference.signingUpRequest();
            inValue.Body = new BloodPressureTracker.SignUpServiceReference.signingUpRequestBody();
            inValue.Body.name = name;
            inValue.Body.weight = weight;
            inValue.Body.age = age;
            inValue.Body.gender = gender;
            inValue.Body.bloodPressure = bloodPressure;
            inValue.Body.email = email;
            inValue.Body.password = password;
            BloodPressureTracker.SignUpServiceReference.signingUpResponse retVal = ((BloodPressureTracker.SignUpServiceReference.SignUpSoap)(this)).signingUp(inValue);
            return retVal.Body.signingUpResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BloodPressureTracker.SignUpServiceReference.signingUpResponse> BloodPressureTracker.SignUpServiceReference.SignUpSoap.signingUpAsync(BloodPressureTracker.SignUpServiceReference.signingUpRequest request) {
            return base.Channel.signingUpAsync(request);
        }
        
        public System.Threading.Tasks.Task<BloodPressureTracker.SignUpServiceReference.signingUpResponse> signingUpAsync(string name, int weight, int age, char gender, string bloodPressure, string email, string password) {
            BloodPressureTracker.SignUpServiceReference.signingUpRequest inValue = new BloodPressureTracker.SignUpServiceReference.signingUpRequest();
            inValue.Body = new BloodPressureTracker.SignUpServiceReference.signingUpRequestBody();
            inValue.Body.name = name;
            inValue.Body.weight = weight;
            inValue.Body.age = age;
            inValue.Body.gender = gender;
            inValue.Body.bloodPressure = bloodPressure;
            inValue.Body.email = email;
            inValue.Body.password = password;
            return ((BloodPressureTracker.SignUpServiceReference.SignUpSoap)(this)).signingUpAsync(inValue);
        }
    }
}
